// 화미옥 김치찌개 - 이미지 경로 매핑
// 생성일: 2026-05-05T04:46:28.518Z
// 항목: 42개 이미지 + 1개 URL
// 사용법: index.html과 같은 폴더에 이 파일과 img/ 폴더를 함께 두세요.

window.HM_IMGS = {
  "band_img_1": "./img/band_img_1.png",
  "band_img_2": "./img/band_img_2.jpg",
  "brandA_bg": "./img/brandA_bg.jpg",
  "brand_visual_img": "./img/brand_visual_img.webp",
  "dinner_bg": "./img/dinner_bg.webp",
  "gallery_1": "./img/gallery_1.png",
  "gallery_2": "./img/gallery_2.jpg",
  "gallery_3": "./img/gallery_3.png",
  "gallery_4": "./img/gallery_4.png",
  "gallery_5": "./img/gallery_5.jpg",
  "gallery_6": "./img/gallery_6.jpg",
  "hero_video": "https://vimeo.com/1183556440?share=copy&fl=sv&fe=ci",
  "hm_0_0": "./img/hm_0_0.png",
  "hm_0_1": "./img/hm_0_1.png",
  "hm_0_2": "./img/hm_0_2.png",
  "hm_0_3": "./img/hm_0_3.png",
  "hm_1_0": "./img/hm_1_0.png",
  "hm_1_1": "./img/hm_1_1.png",
  "hm_1_2": "./img/hm_1_2.png",
  "hm_2_0": "./img/hm_2_0.png",
  "hm_2_1": "./img/hm_2_1.png",
  "hm_3_0": "./img/hm_3_0.png",
  "hm_3_1": "./img/hm_3_1.png",
  "hm_3_2": "./img/hm_3_2.png",
  "hm_3_3": "./img/hm_3_3.png",
  "interior_main": "./img/interior_main.webp",
  "interior_sub_0": "./img/interior_sub_0.webp",
  "interior_sub_1": "./img/interior_sub_1.webp",
  "interior_sub_2": "./img/interior_sub_2.webp",
  "lunch_bg": "./img/lunch_bg.webp",
  "process_bg": "./img/process_bg.webp",
  "review_img_0": "./img/review_img_0.webp",
  "review_img_1": "./img/review_img_1.webp",
  "review_img_2": "./img/review_img_2.webp",
  "review_img_3": "./img/review_img_3.webp",
  "step_img_0": "./img/step_img_0.webp",
  "step_img_1": "./img/step_img_1.webp",
  "step_img_2": "./img/step_img_2.webp",
  "suitable_bg": "./img/suitable_bg.webp",
  "why_img_0": "./img/why_img_0.webp",
  "why_img_1": "./img/why_img_1.webp",
  "why_img_2": "./img/why_img_2.webp",
  "why_img_3": "./img/why_img_3.webp"
};
